<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGplwsjm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGplwsjm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGplwsjm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGplwsjm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGplwsjm\appProdProjectContainer([
    'container.build_hash' => 'Gplwsjm',
    'container.build_id' => '9cf5e5cc',
    'container.build_time' => 1645184022,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGplwsjm');
