<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpnb2k6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpnb2k6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFpnb2k6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFpnb2k6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFpnb2k6\appProdProjectContainer([
    'container.build_hash' => 'Fpnb2k6',
    'container.build_id' => '533d9866',
    'container.build_time' => 1645184047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpnb2k6');
