{*
* 2017 Azelab
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Azelab <support@azelab.com>
*  @copyright  2017 Azelab
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Azelab
*}
<div class="arcontactus-config-panel {if $active_tab != 'ArContactUsButtonConfig' && $active_tab != 'ArContactUsButtonMobileConfig'}hidden{/if}" id="arcontactus-button">
    <div class="panel">
        <div class="panel-heading">
            <i class="icon-info"></i> {l s='Button settings' mod='arcontactus'}
        </div>
        <div class="form-wrapper">
            <ul class="nav nav-tabs">
                <li class="{if $active_tab != 'ArContactUsButtonMobileConfig'}active{/if}">
                    <a href="#arcu-button-desktop" id="arcu-button-desktop-tab" data-toggle="tab">{l s='Desktop' mod='arcontactus'}</a>
                </li>
                <li class="{if $active_tab == 'ArContactUsButtonMobileConfig'}active{/if}">
                    <a href="#arcu-button-mobile" id="arcu-button-desktop-tab" data-toggle="tab">{l s='Mobile' mod='arcontactus'}</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane {if $active_tab != 'ArContactUsButtonMobileConfig'}active{/if}" id="arcu-button-desktop">
                    {$form->generateForm($buttonFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
                </div>
                <div class="tab-pane {if $active_tab == 'ArContactUsButtonMobileConfig'}active{/if}" id="arcu-button-mobile">
                    {$form->generateForm($buttonMobileFormParams) nofilter}{* HTML content generated by HelperForm, no escape necessary *}
                </div>
            </div>
        </div>
    </div>
    
</div>